<?php
// api/download_recipe_pdf.php

// Set content type
header('Content-Type: application/json');

// Check if request is POST
if ($_SERVER['REQUEST_METHOD'] !== 'POST') {
    echo json_encode(['success' => false, 'error' => 'Invalid request method']);
    exit;
}

// Get recipe text from POST data
$recipe_text = isset($_POST['recipe_text']) ? $_POST['recipe_text'] : '';

if (empty($recipe_text)) {
    echo json_encode(['success' => false, 'error' => 'Recipe text is required']);
    exit;
}

// Try to generate the PDF
try {
    // Include mPDF library
    require_once __DIR__ . '/../vendor/autoload.php';

    // Create an instance of mPDF
    $mpdf = new \Mpdf\Mpdf([
        'mode' => 'utf-8', 
        'format' => 'A4',
        'margin_top' => 20,
        'margin_right' => 15,
        'margin_bottom' => 20,
        'margin_left' => 15
    ]);

    // Set document information
    $mpdf->SetTitle('SpiceShelf AI Recipe');
    $mpdf->SetAuthor('SpiceShelf');
    
    // Format recipe text (replace \n with <br> for HTML)
    $formatted_recipe = nl2br($recipe_text);
    
    // Add some styling
    $stylesheet = "
        body { font-family: 'Poppins', sans-serif; color: #333; }
        h1 { color: #F29E52; text-align: center; margin-bottom: 25px; }
        h2 { color: #A8B545; margin-top: 20px; }
        .recipe-section { margin-bottom: 20px; }
        .footer { text-align: center; font-size: 12px; color: #888; margin-top: 30px; }
    ";
    
    // Parse the recipe to extract title, ingredients, steps
    $lines = explode("\n", $recipe_text);
    $recipe_name = '';
    
    // Try to extract recipe name from first line
    if (!empty($lines[0]) && strpos($lines[0], 'Recipe name:') !== false) {
        $recipe_name = trim(str_replace('Recipe name:', '', $lines[0]));
    }
    
    // Build HTML content
    $html = '
    <html>
    <head>
        <style>' . $stylesheet . '</style>
    </head>
    <body>
        <h1>' . (!empty($recipe_name) ? htmlspecialchars($recipe_name) : 'AI Generated Recipe') . '</h1>
        <div class="recipe-content">' . $formatted_recipe . '</div>
        <div class="footer">Generated by SpiceShelf AI Recipe Generator</div>
    </body>
    </html>';
    
    // Write HTML content to the PDF
    $mpdf->WriteHTML($html);
    
    // Create a unique filename
    $filename = 'SpiceShelf_Recipe_' . date('Y-m-d_H-i-s') . '.pdf';
    
    // Save to temporary file
    $temp_file = __DIR__ . '/../temp/' . $filename;
    
    // Ensure temp directory exists
    if (!is_dir(__DIR__ . '/../temp/')) {
        mkdir(__DIR__ . '/../temp/', 0755, true);
    }
    
    // Save PDF to file
    $mpdf->Output($temp_file, 'F');
    
    // Return success with the filename for download
    echo json_encode([
        'success' => true, 
        'filename' => $filename,
        'download_url' => 'api/download_pdf.php?file=' . urlencode($filename)
    ]);
    
} catch (Exception $e) {
    echo json_encode(['success' => false, 'error' => 'PDF generation failed: ' . $e->getMessage()]);
}